services:
    nicosomb.wallabag.subscriber.webarchive:
        class: Nicosomb\WallabagWebarchiveBundle\Event\Subscriber\WebarchiveSubscriber
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "%nicosomb_wallabag_webarchive.enabled%"
            - "@nicosomb.wallabag.entry.webarchive"
            - "@wallabag_core.content_proxy"
            - "@logger"
        tags:
            - { name: kernel.event_subscriber }

    nicosomb.wallabag.entry.webarchive.client:
        class: GuzzleHttp\Client

    nicosomb.wallabag.entry.webarchive:
        class: Nicosomb\WallabagWebarchiveBundle\Helper\Webarchive
        arguments:
            - "@nicosomb.wallabag.entry.webarchive.client"
            - "@logger"
